### ISSUE TITLE
./gradlew packages fails with a missing dependency 

### ISSUE THREAD

**Issue by julianharty** [HabchiSarra/Sniffer#2]
I git cloned your project and tried to build it using the instructions in your [README](https://github.com/HabchiSarra/Sniffer/blob/develop/README.md). The gradle task failed
```
$ ./gradlew packages

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':packages'.
> Task with path 'GitHubMiner:shadowJar' not found in root project 'Sniffer'.
```
Please can you help resolve whatever's wrong? e.g. is the dependency out of date?

https://github.com/HabchiSarra/Sniffer/blob/develop/build.gradle uses 2.0.0
` classpath "com.github.jengelman.gradle.plugins:shadow:2.0.0"}`

https://imperceptiblethoughts.com/shadow/getting-started/#default-java-groovy-tasks recommends version 5.0.0
`classpath 'com.github.jengelman.gradle.plugins:shadow:5.0.0'`

But perhaps I'm looking in the wrong place?

**Comment by aveuiller** [comment]
Hello @julianharty ,

Thanks for the issue, the project is quite young and it seems to be a missed point in the documentation. :) 

As a matter of fact, this project is relying on submodules, so you have to initialize them before using the provided commands.
If you run the command `git submodule init && git submodule update`, the former `./gradlew packages` should work just file. I will update the README with it.

Do not hesitate to report any other issue you may have with Sniffer.

**Comment by aveuiller** [comment]
I'm closing the issue since your problem should be fixed by now. Don't hesitate to open it again if you still have troubles with the installation.
